version: 2.1

parameters:
  option1:
    type: string
    default: abc

# Define the jobs we want to run for this project
jobs:
  build:
    steps:
      - run:
          command: |
            echo "<< parameters.option1 >> - build"
  test:
    steps:
      steps:
      - run:
          command: |
            echo "<< parameters.option1 >> - test"
  deploy:
    steps:
      - run:
        command: |
            echo "<< parameters.option1 >> - test"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - build
            - test
      - deploy:
          requires:
            - hold
